- name: Rundeck | update basic security to have users
  template:
    src: realm.properties.j2
    dest: /etc/rundeck/realm.properties
    owner: rundeck
    group: rundeck
  when: rundeck_users|length > 0
  notify:
    - restart rundeck
  tags:
    - rundeck
    - users
