---
- name: configure for ldap | ensure LDAP login module configuration exists
  template:
    dest: "{{ rundeck_conf_dir }}/jaas-ldap.conf"
    src: jaas-ldap.conf.j2
    owner: "{{ rundeck_user }}"
    group: "{{ rundeck_group }}"
    mode: 0640

- name: configure for ldap | ensure profile is updated to use LDAP configuration
  replace:
    path: "{{ rundeck_conf_dir }}/profile"
    regexp: '-Djava\.security\.auth\.login\.config=(.*)'
    replace: '-Djava.security.auth.login.config={{ rundeck_conf_dir }}/jaas-ldap.conf \\'
  when: ansible_os_family == 'Debian'
  notify:
    - restart rundeck
  tags:
    - rundeck
    - configuration
    - ldap

- name: configure for ldap | ensure /etc/sysconfig/rundeckd exists
  file:
    path: /etc/sysconfig/rundeckd
    state: touch
  when: ansible_os_family == 'RedHat'
  tags:
    - rundeck
    - configuration
    - ldap

- name: configure for ldap | ensure overrides exists in /etc/sysconfig/rundeckd
  lineinfile:
    path: /etc/sysconfig/rundeckd
    line: "{{ item }}"
  when: ansible_os_family == 'RedHat'
  with_items:
    - "JAAS_CONF={{ rundeck_conf_dir }}/jaas-ldap.conf"
    - "LOGIN_MODULE=ldap"
  notify:
    - restart rundeck
  tags:
    - rundeck
    - configuration
    - ldap

- name: configure for ldap | ensure profile is updated to use LDAP module
  replace:
    dest: "{{ rundeck_conf_dir }}/profile"
    regexp: '^(\s*)-Dloginmodule.name=(.*)$'
    replace: '\1-Dloginmodule.name=ldap \\'
  notify:
    - restart rundeck
  tags:
    - rundeck
    - configuration
    - ldap

- name: configure for ldap | install stunnel4 for google secure ldap
  block:
  - name: configure for ldap | install stunnel4
    package:
      name: stunnel4
      state: latest
    become: yes
    notify:
      - restart stunnel4

  - name: configure for ldap | configure stunnel4 for google secure ldap
    template:
      dest: "/etc/stunnel/google-ldap.conf"
      src: google-ldap.conf.j2
    notify:
    - restart stunnel4

  - name: Checking rundeck_ldap_google_crt variable
    fail: msg="You must specify a Certificate for Google LDAP with variable rundeck_ldap_google_crt"
    when: rundeck_ldap_google_crt == ''

  - name: Checking rundeck_ldap_google_key variable
    fail: msg="You must specify a Key for Google LDAP with variable rundeck_ldap_google_key"
    when: rundeck_ldap_google_key == ''

  - name: configure for ldap | set google certificate file
    copy:
      dest: /etc/stunnel/google-ldap-client.crt
      content: "{{ rundeck_ldap_google_crt }}"
    notify:
    - restart stunnel4

  - name: configure for ldap | set google key file
    copy:
      dest: /etc/stunnel/google-ldap-client.key
      content: "{{ rundeck_ldap_google_key }}"
    notify:
    - restart stunnel4

  when: rundeck_ldap_google
