---
- name: Rundeck - PostgreSQL | make server lib directory
  file:
    group: rundeck
    mode: 0655
    owner: rundeck
    path: /var/lib/rundeck/lib
    state: directory
  tags:
    - rundeck
    - directory
    - postgresql

- name: Rundeck - PostgreSQL | download postgreSQL jdbc driver
  get_url:
    dest: "/var/lib/rundeck/lib/{{ rundeck_postgresql_driver_file }}"
    url: "{{ rundeck_postgresql_driver_download }}"
    group: rundeck
    mode: 0655
    owner: rundeck
    validate_certs: no  # work around to certificate on ubuntu 14.04.
  tags:
    - rundeck
    - jdbc
    - postgresql
