---
- name: Rundeck - PostgreSQL | make server lib directory
  file:
    group: "{{ rundeck_group }}"
    mode: 0755
    owner: "{{ rundeck_user }}"
    path: /var/lib/rundeck/lib
    state: directory

- name: Rundeck - PostgreSQL | download postgreSQL jdbc driver
  get_url:
    dest: "/var/lib/rundeck/lib/{{ rundeck_postgresql_driver_file }}"
    url: "{{ rundeck_postgresql_driver_download }}"
    group: "{{ rundeck_group }}"
    mode: 0644
    owner: "{{ rundeck_user }}"
    validate_certs: no  # work around to certificate on ubuntu 14.04.
