---
# Debian based OS
- name: Rundeck | Install supporting packages
  apt:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - python-pip

- name: Rundeck | Install supporting python packages
  pip:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
    - httplib2

- name: Rundeck | Add Bintray GPG key for rundeck repo
  apt_key:
    id: 379CE192D401AB61
    url: https://bintray.com/user/downloadSubjectPublicKey?username=bintray
  tags:
    - rundeck
    - install
    - packages

- name: Rundeck | Add Rundeck APT repository on Bintray
  apt_repository:
    repo: 'deb http://dl.bintray.com/rundeck/rundeck-deb /'
    filename: rundeck
  tags:
    - rundeck
    - install
    - packages

- name: Rundeck | install from APT repository
  apt:
    name: "rundeck{{ (rundeck_version == '') | ternary('', '=' + rundeck_version) }}"
    state: present
    allow_unauthenticated: yes #FIXME: https://github.com/rundeck/rundeck/issues/93
  notify:
    - systemd daemon-reload
    - restart rundeck
  tags:
    - rundeck
    - install
    - packages

- name: Rundeck | install rundeck CLI
  apt:
    name: "rundeck-cli"
    state: present
    allow_unauthenticated: yes #FIXME: https://github.com/rundeck/rundeck/issues/93
  when: rundeck_install_cli
  tags:
    - rundeck
    - install
    - packages


- name: Rundeck | ensure service log directory has correct ownership
  file:
    path: /var/log/rundeck
    owner: rundeck
    state: directory
  tags:
    - rundeck
    - install
    - packages

- name: Rundeck | See if there are more log files
  find:
    paths: /var/log/rundeck
    file_type: file
    patterns: "*.log"
  register: rundeck_logfiles
  tags:
    - rundeck
    - install
    - packages

- name: Rundeck | ensure service log files have correct ownership
  file:
    path: "{{ item.path }}"
    owner: rundeck
    state: file
  with_items:
    "{{ rundeck_logfiles.files }}"
  tags:
    - rundeck
    - install
    - packages

- name: Rundeck | ensure service rundeckd is started and enabled
  systemd:
    name: rundeckd
    state: started
    enabled: yes
    daemon_reload: yes
