---
# Redhat based OS
- name: Rundeck | get rundeck rpm
  yum:
    name: http://repo.rundeck.org/latest.rpm
    state: present
  become: yes

- name: Rundeck | get rundeck rpm
  yum:
    name: "rundeck{{ (rundeck_version == '') | ternary('', '=' + rundeck_version) }}"
    state: present
  become: yes
  notify:
    - start rundeck

- name: install redhat | ensure dependencies are installed
  package:
    name:
      -  libsemanage-python
    state: installed

- name: install redhat | ensure nginx can communicate to jenkins
  seboolean:
    name: httpd_can_network_connect
    state: yes
    persistent: yes
