---
# install rundeck
- include_tasks: install_for_debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: install_for_redhat.yml
  when: ansible_os_family == 'RedHat'

# install rundeck
- include_tasks: configure_for_debian.yml
  when: ansible_os_family == 'Debian'

- include_tasks: configure.yml

# vendor database setup
- include_tasks: configure_for_postgresql.yml
  when: rundeck_database_type == 'postgresql'

- include_tasks: configure_for_mysql.yml
  when: rundeck_database_type == 'mysql'

# user management
- include_tasks: configure_users.yml

# ssh key generation
- include_tasks: configure_ssh.yml
  when: rundeck_generate_ssh == True

# optional LDAP integration
- include_tasks: configure_for_ldap.yml
  when: rundeck_ldap == True

# ACL management
- include_tasks: configure_acl_policies.yml

# extras
- include_tasks: plugins.yml
